[build]
  command = "next build && next export"
  publish = "out"
  functions = "functions"

  [[redirects]]
  from = "/"
  to = "/page3"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["free"]}